services:
  paride-advisory:
    container_name: paride-advisory
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
