import type { FaqItem } from "@/lib/authority-data";

export type ArticleSection = { id: string; title: string; paragraphs: string[]; points?: string[] };
export type Article = {
  slug: string; category: string; title: string; excerpt: string; published: string; updated: string; date: string; readingTime: string;
  image: string; imageAlt: string; pillar: string; service: string; related: string; sections: ArticleSection[]; faqs: FaqItem[];
};

export const articleAuthor = "Paride Sansò Advisory";

export const articles: Article[] = [
  {
    slug: "controllo-di-gestione-pmi-redditivita", category: "Controllo di gestione", title: "Controllo di gestione per PMI: come capire se l’azienda è davvero redditizia", excerpt: "Indicatori, margini e scostamenti per andare oltre il fatturato e leggere la redditività reale dell’impresa.", published: "2026-07-28", updated: "2026-07-28", date: "28 luglio 2026", readingTime: "8 min", image: "/images/service-advisory.jpg", imageAlt: "Analisi di indicatori economici durante un incontro di consulenza",
    pillar: "controllo-di-gestione", service: "amministrativa", related: "analisi-dei-costi-sprechi-margini",
    sections: [
      { id: "fatturato-margine", title: "Fatturato e redditività non sono la stessa cosa", paragraphs: ["Una PMI può aumentare le vendite e, nello stesso periodo, ridurre la propria redditività. Succede quando il mix cambia, gli sconti crescono, i costi variabili aumentano o la struttura assorbe più risorse del previsto.", "Il controllo di gestione serve a collegare il risultato complessivo ai fattori che lo hanno generato. Non sostituisce la contabilità: la rende leggibile per le decisioni operative."], points: ["ricavi per linea, cliente o canale", "margine di contribuzione", "costi fissi e capacità utilizzata", "scostamenti rispetto a budget e periodo precedente"] },
      { id: "kpi", title: "Scegliere pochi KPI che portano a una decisione", paragraphs: ["Un indicatore è utile quando ha una fonte affidabile, una frequenza definita e un responsabile che sa cosa fare in caso di scostamento. Un cruscotto pieno di numeri senza azioni collegate produce soltanto rumore.", "Per una realtà su commessa, per esempio, avanzamento, ore e marginalità prevista possono essere più importanti del solo fatturato mensile. In un’attività commerciale contano invece rotazione, margine per categoria e valore medio della vendita."], points: ["partire dalle decisioni ricorrenti", "definire formula e fonte", "assegnare una soglia di attenzione", "rivedere periodicamente l’utilità del KPI"] },
      { id: "esempio", title: "Un esempio generico: crescita che assorbe margine", paragraphs: ["Immaginiamo un’impresa che acquisisca più ordini grazie a una nuova linea. Il fatturato cresce, ma la linea richiede lavorazioni esterne, urgenze logistiche e più assistenza. Se questi costi non sono attribuiti, la crescita appare positiva mentre il margine unitario si riduce.", "Separare ricavi e costi incrementali permette di verificare se intervenire sul prezzo, sul processo, sui fornitori o sul posizionamento dell’offerta." ] },
      { id: "ritmo", title: "Dal report al ritmo di gestione", paragraphs: ["Il valore nasce dalla continuità: chiusura dei dati, confronto sintetico, decisioni assegnate e verifica. Per molte PMI è preferibile un ciclo mensile stabile a un sistema sofisticato che nessuno riesce ad aggiornare.", "Il primo passo è una diagnosi delle informazioni già disponibili e delle decisioni che oggi vengono prese con maggiore incertezza."] },
    ],
    faqs: [{ question: "Quali dati servono per iniziare?", answer: "Contabilità, vendite, acquisti e dati operativi già disponibili. La qualità viene verificata prima di costruire gli indicatori." }, { question: "Quanto spesso vanno letti i KPI?", answer: "Dipende dalla velocità del fenomeno: cassa e vendite possono richiedere frequenze ravvicinate, mentre altri indicatori sono significativi su base mensile." }],
  },
  {
    slug: "business-plan-cosa-contiene-quando-serve", category: "Pianificazione", title: "Business plan: cosa deve contenere e quando serve davvero", excerpt: "Struttura, ipotesi e scenari di un business plan utile a decidere, non soltanto a presentare un progetto.", published: "2026-07-28", updated: "2026-07-28", date: "28 luglio 2026", readingTime: "9 min", image: "/images/hero-advisory.jpg", imageAlt: "Professionisti che discutono un piano aziendale in un ufficio",
    pillar: "business-plan", service: "finanziaria", related: "cash-flow-aziendale-monitorare-liquidita",
    sections: [
      { id: "quando-serve", title: "Quando il business plan è uno strumento utile", paragraphs: ["Serve quando una decisione modifica in modo rilevante risorse, organizzazione o rischio: nuova attività, investimento, sviluppo di una linea, ingresso di soci o confronto con finanziatori.", "È utile anche senza un destinatario esterno, perché costringe a rendere esplicite ipotesi che altrimenti resterebbero scollegate." ] },
      { id: "contenuti", title: "Le parti che devono essere coerenti tra loro", paragraphs: ["La parte descrittiva chiarisce proposta, clienti, canali, organizzazione e piano di attuazione. La parte numerica traduce queste scelte in ricavi, costi, investimenti, capitale circolante e fonti.", "Il documento è credibile quando ogni numero importante può essere ricondotto a un driver comprensibile."], points: ["sintesi del progetto e obiettivi", "mercato e modello di ricavo", "organizzazione e piano operativo", "conto economico, stato patrimoniale e cash flow", "fabbisogno, fonti e scenari"] },
      { id: "ipotesi", title: "Ipotesi, sensibilità e scenari", paragraphs: ["Una singola previsione può creare falsa precisione. Conviene distinguere scenario base, condizioni meno favorevoli e leve di risposta.", "Un esempio generico è la nuova apertura che raggiunge il volume obiettivo più lentamente del previsto: lo scenario deve mostrare l’effetto sulla cassa e quali costi o investimenti possono essere rimodulati." ] },
      { id: "errori", title: "Gli errori che rendono fragile il piano", paragraphs: ["Previsioni di vendita senza driver, costi sottostimati, IVA e capitale circolante ignorati, investimenti non collegati ai tempi e assenza di responsabilità operative sono errori frequenti.", "Il business plan va infine aggiornato quando cambiano ipotesi sostanziali: non per riscrivere il passato, ma per mantenere utile il confronto tra piano e realtà." ] },
    ],
    faqs: [{ question: "Quanti anni deve coprire?", answer: "L’orizzonte dipende dal progetto e dalla durata degli investimenti. Deve essere abbastanza lungo da mostrare l’equilibrio atteso, senza fingere precisione eccessiva." }, { question: "Chi approva il business plan?", answer: "Il documento supporta decisioni interne o valutazioni esterne, ma non garantisce approvazioni, finanziamenti o risultati." }],
  },
  {
    slug: "consulenza-aziendale-ristoranti-costi-margini", category: "Hospitality", title: "Consulenza aziendale per ristoranti: costi, margini e organizzazione", excerpt: "Come collegare food cost, acquisti, personale, menu e processi per rendere più leggibile la gestione di un ristorante.", published: "2026-07-28", updated: "2026-07-28", date: "28 luglio 2026", readingTime: "9 min", image: "/images/service-advisory.jpg", imageAlt: "Documenti di gestione e laptop utilizzati per analizzare costi e margini",
    pillar: "analisi-dei-costi", service: "amministrativa", related: "controllo-di-gestione-pmi-redditivita",
    sections: [
      { id: "economia", title: "Leggere l’economia del locale oltre l’incasso", paragraphs: ["L’incasso giornaliero è immediato, ma non descrive da solo il risultato. Materie prime, scarti, personale, commissioni, energia e mix delle vendite incidono in tempi e modi differenti.", "La consulenza aziendale aiuta a costruire una lettura periodica che resti collegata al lavoro di cucina, sala, acquisti e amministrazione." ] },
      { id: "food-cost", title: "Food cost e margine: dal calcolo alla gestione", paragraphs: ["Il food cost teorico parte da ricette e quantità standard; quello effettivo riflette acquisti, variazioni di prezzo, scarti e inventari. La differenza tra i due segnala dove approfondire.", "Non esiste una percentuale universale valida per ogni format. Prezzo, proposta, servizio e struttura dei costi vanno letti insieme."], points: ["schede ricetta aggiornate", "prezzi di acquisto e rese", "vendite per prodotto", "scarti e consumi interni", "margine di contribuzione"] },
      { id: "organizzazione", title: "Acquisti, personale e procedure", paragraphs: ["Ordini non pianificati e responsabilità confuse generano urgenze, scorte e rilavorazioni. Calendari, livelli di autorizzazione e controlli semplici migliorano la continuità.", "Anche il costo del personale va collegato ai volumi e ai turni, senza ridurlo a un taglio lineare: l’obiettivo è allineare capacità e qualità del servizio." ] },
      { id: "esempio", title: "Un esempio generico: menu molto venduto, margine debole", paragraphs: ["Un piatto popolare può assorbire margine per ingredienti aumentati, porzioni non uniformi o tempi di preparazione elevati. Il dato suggerisce alternative: rivedere ricetta e porzione, negoziare acquisti, modificare prezzo o promuovere un mix diverso.", "La scelta finale deve considerare anche identità del locale ed esperienza del cliente, non soltanto il foglio di calcolo." ] },
    ],
    faqs: [{ question: "La consulenza vale anche per bar e hotel?", answer: "Sì, ma indicatori e processi vengono adattati al modello specifico; bar, ristoranti e hotel non sono trattati come attività identiche." }, { question: "È necessario cambiare menu o gestionale?", answer: "Non in automatico. Prima si analizzano dati e processi; gli interventi vengono scelti in base alle evidenze." }],
  },
  {
    slug: "cash-flow-aziendale-monitorare-liquidita", category: "Finanza", title: "Cash flow aziendale: come monitorare la liquidità e prevenire squilibri", excerpt: "Un metodo pratico per costruire previsioni di cassa, individuare picchi di fabbisogno e aggiornare gli scenari.", published: "2026-07-28", updated: "2026-07-28", date: "28 luglio 2026", readingTime: "8 min", image: "/images/hero-advisory.jpg", imageAlt: "Incontro di pianificazione finanziaria con documenti e computer",
    pillar: "cash-flow", service: "finanziaria", related: "business-plan-cosa-contiene-quando-serve",
    sections: [
      { id: "utile-cassa", title: "Perché utile e cassa seguono tempi diversi", paragraphs: ["Ricavi e costi vengono rilevati secondo criteri economici, mentre la liquidità dipende dal momento effettivo di incassi e pagamenti. Crediti, scorte, imposte e investimenti possono assorbire cassa anche quando il risultato è positivo.", "Per questo il saldo del conto è una fotografia, non una previsione." ] },
      { id: "costruzione", title: "Come costruire una previsione di cassa", paragraphs: ["Si parte dal saldo disponibile e si ordinano entrate e uscite per data attesa. Le voci certe restano separate da quelle stimate, così è possibile capire quale parte del quadro dipende da ipotesi.", "L’orizzonte breve richiede dettaglio; quello medio può aggregare per categorie e scenari."], points: ["incassi da clienti e altri flussi", "fornitori, personale e costi ricorrenti", "imposte e contributi", "investimenti e finanziamenti", "saldo minimo e margine di sicurezza"] },
      { id: "circolante", title: "Capitale circolante: le leve operative", paragraphs: ["Tempi di incasso, condizioni di pagamento e livello delle scorte trasformano vendite e acquisti in fabbisogno. Migliorare il cash flow non significa soltanto cercare nuova finanza: spesso richiede intervenire sui processi.", "Un esempio generico è una crescita sostenuta da ordini importanti che richiedono acquisti anticipati e pagamenti del cliente molto successivi. Il margine può essere positivo, ma il picco di cassa va coperto." ] },
      { id: "routine", title: "Aggiornare il forecast e decidere", paragraphs: ["La previsione deve essere confrontata con i movimenti effettivi, correggendo tempi e ipotesi. Le differenze ricorrenti indicano un processo da migliorare, non solo una cella da aggiornare.", "Soglie di attenzione e responsabilità chiare permettono di agire su incassi, acquisti, investimenti o fonti con tempo sufficiente." ] },
    ],
    faqs: [{ question: "Qual è la frequenza migliore?", answer: "Per la tesoreria operativa può essere settimanale; per una visione più ampia mensile. La frequenza deve seguire volatilità e rischio." }, { question: "Il cash flow sostituisce il budget?", answer: "No. Il budget economico e il cash flow rispondono a domande diverse e devono essere coerenti tra loro." }],
  },
  {
    slug: "analisi-dei-costi-sprechi-margini", category: "Gestione", title: "Analisi dei costi: come individuare sprechi e proteggere i margini", excerpt: "Classificare costi e driver per distinguere risorse necessarie, inefficienze e opportunità di miglioramento.", published: "2026-07-28", updated: "2026-07-28", date: "28 luglio 2026", readingTime: "8 min", image: "/images/service-advisory.jpg", imageAlt: "Analisi operativa dei costi su documenti aziendali",
    pillar: "analisi-dei-costi", service: "amministrativa", related: "controllo-di-gestione-pmi-redditivita",
    sections: [
      { id: "classificare", title: "Classificare i costi in base alla decisione", paragraphs: ["La stessa spesa può essere letta in modi diversi. Distinguere fisso e variabile aiuta a valutare i volumi; distinguere diretto e indiretto aiuta ad attribuire il costo a prodotti o servizi.", "La classificazione non è un esercizio teorico: va scelta in funzione della domanda a cui si vuole rispondere." ] },
      { id: "driver", title: "Cercare i driver, non soltanto le voci contabili", paragraphs: ["Una voce aggregata indica quanto è stato speso, ma non sempre perché. Ordini urgenti, errori, rilavorazioni, bassa saturazione e complessità del catalogo possono essere driver più utili della categoria contabile.", "Collegare il costo al processo rende possibile un intervento concreto."], points: ["volumi e mix", "tempi e capacità", "qualità e rilavorazioni", "condizioni di acquisto", "complessità operativa"] },
      { id: "margine", title: "Margine di contribuzione e punto di pareggio", paragraphs: ["Il margine di contribuzione mostra quanto resta dopo i costi variabili per coprire la struttura. Il punto di pareggio traduce questa relazione in un volume indicativo.", "Sono strumenti di scenario, non certezze: se prezzo, mix o costi cambiano, anche il risultato va aggiornato." ] },
      { id: "azioni", title: "Dall’analisi al piano di miglioramento", paragraphs: ["Le azioni possono riguardare prezzo, offerta, processo, fornitori, capacità o eliminazione di attività prive di valore. Vanno ordinate per impatto, fattibilità e rischio.", "Un controllo successivo verifica se il risparmio previsto è reale e se non ha prodotto effetti negativi su qualità, vendite o continuità." ] },
    ],
    faqs: [{ question: "Qual è il primo costo da analizzare?", answer: "Quello più rilevante o più variabile rispetto al risultato, purché sia collegabile a un processo e a una decisione." }, { question: "Come si attribuiscono i costi indiretti?", answer: "Con criteri ragionevoli e documentati. L’obiettivo è sostenere decisioni, evitando precisione apparente o ripartizioni arbitrarie." }],
  },
  {
    slug: "project-management-riqualificazione", category: "Project management", title: "Riqualificazione immobiliare: perché il coordinamento fa la differenza", excerpt: "Tempi, decisioni, costi e fornitori: una regia operativa rende più leggibile un progetto complesso.", published: "2026-05-06", updated: "2026-07-28", date: "Aggiornato il 28 luglio 2026", readingTime: "7 min", image: "/images/service-advisory.jpg", imageAlt: "Riunione di coordinamento per un progetto tecnico",
    pillar: "project-management", service: "project-management", related: "analisi-dei-costi-sprechi-margini",
    sections: [
      { id: "complessita", title: "La complessità nasce dalle dipendenze", paragraphs: ["Una riqualificazione coinvolge decisioni tecniche, autorizzazioni, forniture, accessi e vincoli operativi. Anche attività semplici possono bloccarsi se una dipendenza emerge troppo tardi.", "Il coordinamento rende visibili sequenza, responsabili e informazioni necessarie, senza sostituire progettisti, direttori lavori o imprese." ] },
      { id: "piano", title: "Un piano condiviso e aggiornabile", paragraphs: ["Il piano deve distinguere milestone, decisioni del committente, attività dei professionisti e consegne dei fornitori. Aggiornarlo significa esplicitare conseguenze e alternative, non nascondere i ritardi."], points: ["perimetro e obiettivi", "responsabilità", "dipendenze e milestone", "rischi e decisioni aperte", "modalità di reporting"] },
      { id: "costi", title: "Controllare costi e varianti", paragraphs: ["Il budget iniziale va collegato a preventivi, impegni, pagamenti e varianti. Una modifica può avere effetti su più attività e deve essere valutata prima dell’approvazione.", "Un registro decisioni aiuta a ricostruire motivazioni, responsabilità e impatti." ] },
      { id: "comunicazione", title: "Comunicazione proporzionata al progetto", paragraphs: ["Riunioni frequenti senza informazioni aggiornate non migliorano il controllo. È preferibile un reporting sintetico: avanzamento, criticità, decisioni richieste e prossimi passi.", "Le attività professionali riservate restano in capo ai soggetti competenti e regolarmente abilitati." ] },
    ],
    faqs: [{ question: "Il coordinamento sostituisce la direzione lavori?", answer: "No. Sono ruoli distinti; le attività tecniche riservate restano ai professionisti abilitati." }, { question: "Quando conviene introdurre una regia?", answer: "Prima dell’avvio operativo, quando è ancora possibile chiarire perimetro, dipendenze e responsabilità." }],
  },
];
