import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { CtaBanner } from "@/components/cta-banner";
import { PageHero } from "@/components/page-hero";
import { ServicesGrid } from "@/components/services-grid";
import { authorityPages } from "@/lib/authority-data";
import { createMetadata } from "@/lib/seo";
export const metadata = createMetadata({ title: "Servizi", description: "Consulenza aziendale a Milano e in tutta Italia: amministrazione, finanza, strategia, servizi tecnici e project management.", path: "/servizi" });
export default function ServicesPage() { return <><PageHero eyebrow="Servizi" title="La consulenza giusta, collegata ai tuoi obiettivi." description="Cinque aree complementari e competenze specifiche per dare struttura alle decisioni, a Milano e anche da remoto in tutta Italia." /><section className="container py-20 sm:py-28"><h2 className="sr-only">Aree di servizio</h2><ServicesGrid /></section><section className="bg-slate-50 py-20 sm:py-28"><div className="container"><p className="eyebrow">Competenze</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-.04em] text-navy sm:text-4xl">Approfondisci il tema che incide sulla tua prossima decisione.</h2><div className="mt-10 grid gap-x-8 gap-y-1 md:grid-cols-2 lg:grid-cols-3">{authorityPages.map((page) => <Link className="group flex items-center justify-between gap-3 border-t border-slate-200 py-4 text-sm font-semibold text-navy transition hover:text-gold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold" href={`/competenze/${page.slug}`} key={page.slug}>{page.title}<ArrowUpRight className="size-4 shrink-0 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></Link>)}</div></div></section><CtaBanner title="Hai un’esigenza specifica?" description="Partiamo da una conversazione per definire il supporto più utile." /></>; }
