import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { CtaBanner } from "@/components/cta-banner";
import { articles, siteConfig } from "@/lib/site-data";
import { createMetadata } from "@/lib/seo";
export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles.find((item) => item.slug === slug); return article ? createMetadata({ title: article.title, description: article.excerpt, path: `/blog/${article.slug}` }) : {}; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = articles.find((item) => item.slug === slug); if (!article) notFound(); const sections = ["Definire gli obiettivi prima degli strumenti", "Costruire un quadro informativo essenziale", "Trasformare le analisi in decisioni operative"]; const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.url }, { "@type": "ListItem", position: 2, name: "Insights", item: `${siteConfig.url}/blog` }, { "@type": "ListItem", position: 3, name: article.title }] }; return <><article className="container max-w-4xl py-16 sm:py-24"><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-semibold text-navy"><ArrowLeft className="size-4" /> Tutti gli insights</Link><p className="eyebrow mt-12">{article.category}</p><h1 className="mt-5 text-4xl font-semibold tracking-[-0.055em] text-navy sm:text-6xl">{article.title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{article.excerpt}</p><p className="mt-8 text-sm text-slate-500">{article.date} · {article.readingTime} di lettura</p><div className="mt-12 space-y-10 text-lg leading-8 text-slate-700">{sections.map((heading) => <section key={heading}><h2 className="text-2xl font-semibold tracking-[-0.03em] text-navy">{heading}</h2><p className="mt-4">La crescita sostenibile nasce da un metodo: osservare il contesto, scegliere poche priorità misurabili e verificare con continuità l’efficacia delle azioni intraprese. Un confronto multidisciplinare aiuta a collegare numeri, persone e operatività.</p></section>)}</div></article><CtaBanner /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /></>; }
