import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Clock3 } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { CtaBanner } from "@/components/cta-banner";
import { articleAuthor, articles } from "@/lib/articles";
import { authorityPages } from "@/lib/authority-data";
import { createMetadata } from "@/lib/seo";
import { services, siteConfig } from "@/lib/site-data";

export const dynamicParams = false;
export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles.find((item) => item.slug === slug); return article ? createMetadata({ title: article.title, description: article.excerpt, path: `/blog/${article.slug}`, type: "article", publishedTime: article.published, modifiedTime: article.updated }) : {}; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const article = articles.find((item) => item.slug === slug); if (!article) notFound();
  const pillar = authorityPages.find((item) => item.slug === article.pillar)!; const service = services.find((item) => item.slug === article.service)!; const related = articles.find((item) => item.slug === article.related)!; const url = `${siteConfig.url}/blog/${article.slug}`;
  const jsonLd = [{ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.excerpt, image: new URL(article.image, siteConfig.url).toString(), datePublished: article.published, dateModified: article.updated, author: { "@type": "Organization", name: articleAuthor, url: siteConfig.url }, publisher: { "@type": "Organization", name: siteConfig.name, url: siteConfig.url }, mainEntityOfPage: { "@type": "WebPage", "@id": url } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.url }, { "@type": "ListItem", position: 2, name: "Insights", item: `${siteConfig.url}/blog` }, { "@type": "ListItem", position: 3, name: article.title, item: url }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: article.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }];
  return <>
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Insights", href: "/blog" }, { label: article.title }]} />
    <article><header className="container max-w-5xl py-12 sm:py-20"><p className="eyebrow">{article.category}</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.055em] text-navy sm:text-6xl">{article.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">{article.excerpt}</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500"><span>Di {articleAuthor}</span><time dateTime={article.updated}>{article.date}</time><span className="flex items-center gap-1"><Clock3 className="size-4" />{article.readingTime} di lettura</span></div></header>
    <div className="relative mx-auto aspect-[16/8] max-w-6xl overflow-hidden bg-navy"><Image src={article.image} alt={article.imageAlt} fill priority sizes="(min-width: 1280px) 1152px, 100vw" className="object-cover opacity-80" /></div>
    <div className="container grid max-w-6xl gap-12 py-16 lg:grid-cols-[260px_1fr]"><aside><nav aria-label="Indice dell’articolo" className="sticky top-28 border-l-2 border-gold pl-5"><p className="text-sm font-bold text-navy">In questo articolo</p><ol className="mt-4 space-y-3 text-sm text-slate-600">{article.sections.map((section) => <li key={section.id}><a className="transition hover:text-navy focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold" href={`#${section.id}`}>{section.title}</a></li>)}</ol></nav></aside><div className="min-w-0 space-y-14 text-lg leading-8 text-slate-700">{article.sections.map((section) => <section className="scroll-mt-28" id={section.id} key={section.id}><h2 className="text-3xl font-semibold tracking-[-.04em] text-navy">{section.title}</h2>{section.paragraphs.map((paragraph) => <p className="mt-5" key={paragraph}>{paragraph}</p>)}{section.points && <ul className="mt-6 grid gap-3 sm:grid-cols-2">{section.points.map((point) => <li className="border-l-2 border-gold bg-slate-50 px-5 py-3 text-base text-navy" key={point}>{point}</li>)}</ul>}</section>)}</div></div>
    <section className="bg-slate-50 py-16"><div className="container grid max-w-6xl gap-4 md:grid-cols-3"><ContextLink label="Pillar" title={pillar.title} href={`/competenze/${pillar.slug}`} /><ContextLink label="Servizio" title={service.title} href={`/servizi/${service.slug}`} /><ContextLink label="Articolo correlato" title={related.title} href={`/blog/${related.slug}`} /></div></section>
    <section className="container grid max-w-6xl gap-10 py-20 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Domande frequenti</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] text-navy">Per approfondire.</h2></div><div className="divide-y divide-slate-200">{article.faqs.map((faq) => <details className="py-5" key={faq.question}><summary className="cursor-pointer font-semibold text-navy focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold">{faq.question}</summary><p className="mt-3 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></section></article>
    <CtaBanner title="Trasforma l’analisi in un prossimo passo concreto." description="Condividi il contesto: definiamo insieme quali dati e decisioni affrontare per primi." />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
  </>;
}
function ContextLink({ label, title, href }: { label: string; title: string; href: string }) { return <Link className="group flex min-h-40 flex-col justify-between border border-slate-200 bg-white p-5 text-navy transition hover:border-gold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold" href={href}><span className="eyebrow">{label}</span><span className="flex items-end justify-between gap-3 font-semibold">{title}<ArrowUpRight className="size-4 shrink-0" /></span></Link>; }
